# Unit 12 - Tales from the Crypto

---

## 1. Sentiment Analysis

Use the [newsapi](https://newsapi.org/) to pull the latest news articles for Bitcoin and Ethereum and create a DataFrame of sentiment scores for each coin.

Use descriptive statistics to answer the following questions:
1. Which coin had the highest mean positive score?
2. Which coin had the highest negative score?
3. Which coin had the highest positive score?

In [1]:
# Initial imports
import os
import pandas as pd
from dotenv import load_dotenv
import nltk as nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

%matplotlib inline

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\wanda\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [2]:
# Read your api key environment variable
load_dotenv()
api_key = os.getenv('news_api')

In [3]:
# Create a newsapi client
from newsapi import NewsApiClient
newsapi = NewsApiClient(api_key=api_key)

In [4]:
# Fetch the Bitcoin news articles
btc_news = newsapi.get_everything(
    q='bitcoin',
    language='en',
    sort_by='relevancy'
)

In [5]:
# Fetch the Ethereum news articles
eth_news = newsapi.get_everything(
    q='ethereum',
    language='en',
    sort_by='relevancy'
)

In [11]:
# Create the Bitcoin sentiment scores DataFrame
sentiment = []

for articles in btc_news["articles"]:
    try:
        text = articles['content']
        results = analyzer.polarity_scores(text)
        compound = results['compound']
        pos = results['pos']
        neu = results['neu']
        neg = results['neg']
        
        sentiment.append({
            'Compound': compound,
            'Positive': pos,
            'Negative': neg,
            'Neutral': neu,
            'text': text
        })
    except AttributeError:
        pass
    
btc = pd.DataFrame(sentiment)
btc

,Compound,Positive,Negative,Neutral,text
0,-0.3400,0.000,0.061,0.939,When my wife started a little garden in our ur...
1,0.6908,0.178,0.000,0.822,"Like Dogecoin devotees, the mayor of Reno, and..."
2,0.4019,0.080,0.000,0.920,Photo by Joe Raedle/Getty Images\r\n\n \n\n Tw...
3,-0.8860,0.000,0.271,0.729,"By Joe TidyCyber reporter \r\n""Follow the mone..."
4,0.6240,0.127,0.000,0.873,To get a roundup of TechCrunchs biggest and mo...
5,0.2732,0.097,0.000,0.903,"As longtime TechCrunch readers know well, Mich..."
6,0.5719,0.139,0.000,0.861,"After the bell today, Coinbase reported anothe..."
7,0.1280,0.089,0.075,0.836,"SINGAPORE, July 28 (Reuters) - Bitcoin broke a..."
8,0.0000,0.000,0.000,1.000,T-Mobile is grappling with yet another reporte...
9,0.0000,0.000,0.000,1.000,Representations of cryptocurrency Bitcoin are ...
10,-0.4767,0.000,0.088,0.912,James Martin/CNET\r\nA UK man was arrested in ...
11,0.0000,0.000,0.000,1.000,A representation of virtual currency bitcoin i...
12,0.0000,0.000,0.000,1.000,By Reuters Staff\r\nFILE PHOTO: A representati...
13,0.4588,0.083,0.000,0.917,REUTERS/Dado Ruvic/Illustration\r\nWelcome to ...
14,0.0000,0.000,0.000,1.000,Representations of virtual currency bitcoin ar...
15,-0.3818,0.000,0.080,0.920,"LONDON, July 20 (Reuters) - Bitcoin fell on Tu..."
16,-0.2960,0.052,0.089,0.859,By Reuters Staff\r\nAmazon app is seen on a sm...
17,0.0000,0.000,0.000,1.000,Posted \r\nTesla is likely to start taking bit...
18,0.5106,0.129,0.000,0.871,22 with 21 posters participating\r\nAmazon pos...
19,0.0000,0.000,0.000,1.000,Representations of cryptocurrencies Bitcoin an...

In [12]:
# Create the Ethereum sentiment scores DataFrame
sentiment = []

for articles in eth_news["articles"]:
    try:
        text = articles['content']
        results = analyzer.polarity_scores(text)
        compound = results['compound']
        pos = results['pos']
        neu = results['neu']
        neg = results['neg']
        
        sentiment.append({
            'Compound': compound,
            'Positive': pos,
            'Negative': neg,
            'Neutral': neu,
            'text': text
        })
    except AttributeError:
        pass
    
eth = pd.DataFrame(sentiment)
eth

,Compound,Positive,Negative,Neutral,text
0,0.3612,0.075,0.000,0.925,There are many blockchain platforms competing ...
1,-0.2411,0.000,0.061,0.939,Blockchain infrastructure startups are heating...
2,0.6956,0.190,0.000,0.810,Cent was founded in 2017 as an ad-free creator...
3,0.5719,0.139,0.000,0.861,"After the bell today, Coinbase reported anothe..."
4,0.0000,0.000,0.000,1.000,Representation of the Ethereum virtual currenc...
5,0.0000,0.000,0.000,1.000,"HONG KONG, Aug 5 (Reuters) - Ether held near t..."
6,0.0000,0.000,0.000,1.000,Representations of cryptocurrencies Bitcoin an...
7,0.3400,0.105,0.000,0.895,Cryptocurrencies spiked Monday after Amazon li...
8,-0.3612,0.050,0.094,0.855,"By Mary-Ann RussonBusiness reporter, BBC News\..."
9,0.6369,0.157,0.000,0.843,"""Anthony Di Iorio, a co-founder of the Ethereu..."
10,0.0000,0.000,0.000,1.000,Representations of cryptocurrency Ethereum are...
11,0.2263,0.048,0.000,0.952,More than $144 million worth of ether has been...
12,0.2263,0.056,0.000,0.944,The ethereum network runs the ether cryptocurr...
13,0.0000,0.000,0.000,1.000,All the sessions from Transform 2021 are avail...
14,-0.3400,0.000,0.072,0.928,This article was translated from our Spanish e...
15,-0.4404,0.000,0.079,0.921,Miners are the heart of a system known as proo...
16,0.0000,0.000,0.000,1.000,Shopify has made it possible for eligible sell...
17,0.5346,0.158,0.000,0.842,Personal Finance Insider writes about products...
18,0.0000,0.000,0.000,1.000,Representations of cryptocurrencies Bitcoin an...
19,0.1779,0.069,0.046,0.885,NEW YORK (Reuters) - Bitcoin investment produc...

In [13]:
# Describe the Bitcoin Sentiment
btc.describe()

        Compound   Positive   Negative    Neutral
count  20.000000  20.000000  20.000000  20.000000
mean    0.063935   0.048700   0.033200   0.918100
std     0.410191   0.060552   0.066017   0.076228
min    -0.886000   0.000000   0.000000   0.729000
25%    -0.074000   0.000000   0.000000   0.868500
50%     0.000000   0.000000   0.000000   0.918500
75%     0.416125   0.091000   0.064500   1.000000
max     0.690800   0.178000   0.271000   1.000000

In [14]:
# Describe the Ethereum Sentiment
eth.describe()

        Compound   Positive   Negative    Neutral
count  20.000000  20.000000  20.000000  20.000000
mean    0.119400   0.052350   0.017600   0.930000
std     0.332101   0.064716   0.032365   0.064286
min    -0.440400   0.000000   0.000000   0.810000
25%     0.000000   0.000000   0.000000   0.879000
50%     0.000000   0.024000   0.000000   0.933500
75%     0.345300   0.082500   0.011500   1.000000
max     0.695600   0.190000   0.094000   1.000000

### Questions:

Q: Which coin had the highest mean positive score?

A: ethereum

Q: Which coin had the highest compound score?

A: ethereum

Q. Which coin had the highest positive score?

A: ethereum

---

## 2. Natural Language Processing
---
###   Tokenizer

In this section, you will use NLTK and Python to tokenize the text for each coin. Be sure to:
1. Lowercase each word.
2. Remove Punctuation.
3. Remove Stopwords.

In [15]:
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
from string import punctuation
import re

In [29]:
# Instantiate the lemmatizer
wnl = WordNetLemmatizer()

# Create a list of stopwords
stop = stopwords.words('english')

# Expand the default stopwords list if necessary
stop.append("'s")
stop.append('it')
stop.append("n't")
stop = set(stop)

In [30]:
# Complete the tokenizer function
def tokenizer(text):
    """Tokenizes text."""
  
    # Create a tokenized list of the words
    words = word_tokenize(text)
   
    # Convert the words to lowercase
    words = list(filter(lambda w: w.lower(), words))
    
    # Remove the stop words
    words = list(filter(lambda t: t.lower() not in stop, words))
    
    # Remove the punctuation from text
    words = list(filter(lambda t: t not in punctuation, words))
                 
    # Lemmatize words into root words
    tokens = [wnl.lemmatize(word) for word in words]
    
    return tokens

In [31]:
# Create a new tokens column for Bitcoin
btc['tokens'] = btc.text.apply(tokenizer)
btc

,Compound,Positive,Negative,Neutral,text,tokens
0,-0.3400,0.000,0.061,0.939,When my wife started a little garden in our ur...,"[wife, started, little, garden, urban, backyar..."
1,0.6908,0.178,0.000,0.822,"Like Dogecoin devotees, the mayor of Reno, and...","[Like, Dogecoin, devotee, mayor, Reno, leader,..."
2,0.4019,0.080,0.000,0.920,Photo by Joe Raedle/Getty Images\r\n\n \n\n Tw...,"[Photo, Joe, Raedle/Getty, Images, Twitter, Sq..."
3,-0.8860,0.000,0.271,0.729,"By Joe TidyCyber reporter \r\n""Follow the mone...","[Joe, TidyCyber, reporter, '', Follow, money, ..."
4,0.6240,0.127,0.000,0.873,To get a roundup of TechCrunchs biggest and mo...,"[get, roundup, TechCrunchs, biggest, important..."
5,0.2732,0.097,0.000,0.903,"As longtime TechCrunch readers know well, Mich...","[longtime, TechCrunch, reader, know, well, Mic..."
6,0.5719,0.139,0.000,0.861,"After the bell today, Coinbase reported anothe...","[bell, today, Coinbase, reported, another, per..."
7,0.1280,0.089,0.075,0.836,"SINGAPORE, July 28 (Reuters) - Bitcoin broke a...","[SINGAPORE, July, 28, Reuters, Bitcoin, broke,..."
8,0.0000,0.000,0.000,1.000,T-Mobile is grappling with yet another reporte...,"[T-Mobile, grappling, yet, another, reported, ..."
9,0.0000,0.000,0.000,1.000,Representations of cryptocurrency Bitcoin are ...,"[Representations, cryptocurrency, Bitcoin, see..."
10,-0.4767,0.000,0.088,0.912,James Martin/CNET\r\nA UK man was arrested in ...,"[James, Martin/CNET, UK, man, arrested, Spain,..."
11,0.0000,0.000,0.000,1.000,A representation of virtual currency bitcoin i...,"[representation, virtual, currency, bitcoin, s..."
12,0.0000,0.000,0.000,1.000,By Reuters Staff\r\nFILE PHOTO: A representati...,"[Reuters, Staff, FILE, PHOTO, representation, ..."
13,0.4588,0.083,0.000,0.917,REUTERS/Dado Ruvic/Illustration\r\nWelcome to ...,"[REUTERS/Dado, Ruvic/Illustration, Welcome, 10..."
14,0.0000,0.000,0.000,1.000,Representations of virtual currency bitcoin ar...,"[Representations, virtual, currency, bitcoin, ..."
15,-0.3818,0.000,0.080,0.920,"LONDON, July 20 (Reuters) - Bitcoin fell on Tu...","[LONDON, July, 20, Reuters, Bitcoin, fell, Tue..."
16,-0.2960,0.052,0.089,0.859,By Reuters Staff\r\nAmazon app is seen on a sm...,"[Reuters, Staff, Amazon, app, seen, smartphone..."
17,0.0000,0.000,0.000,1.000,Posted \r\nTesla is likely to start taking bit...,"[Posted, Tesla, likely, start, taking, bitcoin..."
18,0.5106,0.129,0.000,0.871,22 with 21 posters participating\r\nAmazon pos...,"[22, 21, poster, participating, Amazon, posted..."
19,0.0000,0.000,0.000,1.000,Representations of cryptocurrencies Bitcoin an...,"[Representations, cryptocurrencies, Bitcoin, E..."

In [32]:
# Create a new tokens column for Ethereum
eth['tokens'] = eth.text.apply(tokenizer)
eth

,Compound,Positive,Negative,Neutral,text,tokens
0,0.3612,0.075,0.000,0.925,There are many blockchain platforms competing ...,"[many, blockchain, platform, competing, invest..."
1,-0.2411,0.000,0.061,0.939,Blockchain infrastructure startups are heating...,"[Blockchain, infrastructure, startup, heating,..."
2,0.6956,0.190,0.000,0.810,Cent was founded in 2017 as an ad-free creator...,"[Cent, founded, 2017, ad-free, creator, networ..."
3,0.5719,0.139,0.000,0.861,"After the bell today, Coinbase reported anothe...","[bell, today, Coinbase, reported, another, per..."
4,0.0000,0.000,0.000,1.000,Representation of the Ethereum virtual currenc...,"[Representation, Ethereum, virtual, currency, ..."
5,0.0000,0.000,0.000,1.000,"HONG KONG, Aug 5 (Reuters) - Ether held near t...","[HONG, KONG, Aug, 5, Reuters, Ether, held, nea..."
6,0.0000,0.000,0.000,1.000,Representations of cryptocurrencies Bitcoin an...,"[Representations, cryptocurrencies, Bitcoin, E..."
7,0.3400,0.105,0.000,0.895,Cryptocurrencies spiked Monday after Amazon li...,"[Cryptocurrencies, spiked, Monday, Amazon, lis..."
8,-0.3612,0.050,0.094,0.855,"By Mary-Ann RussonBusiness reporter, BBC News\...","[Mary-Ann, RussonBusiness, reporter, BBC, News..."
9,0.6369,0.157,0.000,0.843,"""Anthony Di Iorio, a co-founder of the Ethereu...","[``, Anthony, Di, Iorio, co-founder, Ethereum,..."
10,0.0000,0.000,0.000,1.000,Representations of cryptocurrency Ethereum are...,"[Representations, cryptocurrency, Ethereum, pl..."
11,0.2263,0.048,0.000,0.952,More than $144 million worth of ether has been...,"[144, million, worth, ether, burned, since, ov..."
12,0.2263,0.056,0.000,0.944,The ethereum network runs the ether cryptocurr...,"[ethereum, network, run, ether, cryptocurrency..."
13,0.0000,0.000,0.000,1.000,All the sessions from Transform 2021 are avail...,"[session, Transform, 2021, available, on-deman..."
14,-0.3400,0.000,0.072,0.928,This article was translated from our Spanish e...,"[article, translated, Spanish, edition, using,..."
15,-0.4404,0.000,0.079,0.921,Miners are the heart of a system known as proo...,"[Miners, heart, system, known, proof, work, pi..."
16,0.0000,0.000,0.000,1.000,Shopify has made it possible for eligible sell...,"[Shopify, made, possible, eligible, seller, se..."
17,0.5346,0.158,0.000,0.842,Personal Finance Insider writes about products...,"[Personal, Finance, Insider, writes, product, ..."
18,0.0000,0.000,0.000,1.000,Representations of cryptocurrencies Bitcoin an...,"[Representations, cryptocurrencies, Bitcoin, E..."
19,0.1779,0.069,0.046,0.885,NEW YORK (Reuters) - Bitcoin investment produc...,"[NEW, YORK, Reuters, Bitcoin, investment, prod..."

---

### NGrams and Frequency Analysis

In this section you will look at the ngrams and word frequency for each coin. 

1. Use NLTK to produce the n-grams for N = 2. 
2. List the top 10 words for each coin.

In [15]:
from collections import Counter
from nltk import ngrams

In [16]:
# Generate the Bitcoin N-grams where N=2
# YOUR CODE HERE!

In [17]:
# Generate the Ethereum N-grams where N=2
# YOUR CODE HERE!

In [18]:
# Function token_count generates the top 10 words for a given coin
def token_count(tokens, N=3):
    """Returns the top N tokens from the frequency count"""
    return Counter(tokens).most_common(N)

In [19]:
# Use token_count to get the top 10 words for Bitcoin
# YOUR CODE HERE!

In [20]:
# Use token_count to get the top 10 words for Ethereum
# YOUR CODE HERE!

---

### Word Clouds

In this section, you will generate word clouds for each coin to summarize the news for each coin

In [21]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import matplotlib as mpl
mpl.rcParams['figure.figsize'] = [20.0, 10.0]

In [22]:
# Generate the Bitcoin word cloud
# YOUR CODE HERE!

In [23]:
# Generate the Ethereum word cloud
# YOUR CODE HERE!

---
## 3. Named Entity Recognition

In this section, you will build a named entity recognition model for both Bitcoin and Ethereum, then visualize the tags using SpaCy.

In [24]:
import spacy
from spacy import displacy

In [25]:
# Download the language model for SpaCy
# !python -m spacy download en_core_web_sm

In [26]:
# Load the spaCy model
nlp = spacy.load('en_core_web_sm')

---
### Bitcoin NER

In [27]:
# Concatenate all of the Bitcoin text together
# YOUR CODE HERE!

In [28]:
# Run the NER processor on all of the text
# YOUR CODE HERE!

# Add a title to the document
# YOUR CODE HERE!

In [29]:
# Render the visualization
# YOUR CODE HERE!

In [30]:
# List all Entities
# YOUR CODE HERE!

---

### Ethereum NER

In [31]:
# Concatenate all of the Ethereum text together
# YOUR CODE HERE!

In [32]:
# Run the NER processor on all of the text
# YOUR CODE HERE!

# Add a title to the document
# YOUR CODE HERE!

In [33]:
# Render the visualization
# YOUR CODE HERE!

In [34]:
# List all Entities
# YOUR CODE HERE!

---